#!/usr/bin/env bash

set -e

echo "Installing ansible..."
if ! [ -x "$(command -v ansible)" ]; then
    # Installs ansible
    sudo apt update
    sudo apt upgrade
    sudo apt install software-properties-common
    sudo add-apt-repository --yes --update ppa:ansible/ansible
    sudo apt install ansible
fi

echo "Creating backup of current configuration..."
[ ! -f ~/.config/gitignore ] || mv ~/.config/gitignore ~/.config/gitignore.bak
[ ! -d ~/.config/nvim ] || mv ~/.config/nvim ~/.config/nvim.bak
[ ! -f ~/.config/terminator/config ] || mv ~/.config/terminator/config  ~/.config/terminator/config.bak
[ ! -f ~/.gitconfig ] || mv ~/.gitconfig ~/.gitconfig.bak
[ ! -f ~/.inputrc ] || mv ~/.inputrc ~/.inputrc.bak
[ ! -d ~/.oh-my-zsh ] || mv ~/.oh-my-zsh ~/.oh-my-zsh.bak
[ ! -f ~/.p10k.zsh ] || mv ~/.p10k.zsh ~/.p10k.zsh.bak
[ ! -d ~/.tmux ] || mv ~/.tmux ~/.tmux.bak
[ ! -f ~/.tmux.conf ] || mv ~/.tmux.conf ~/.tmux.conf.bak
[ ! -f ~/.zshrc ] || mv ~/.zshrc ~/.zshrc.bak
[ ! -f ~/.netrc ] || mv ~/.netrc ~/.netrc.bak

exit 0
