- name: Setup zsh
  hosts: localhost
  become: true
  tasks:
    - name: Update system
      ansible.builtin.apt:
        update_cache: true

    - name: Install zsh
      ansible.builtin.apt:
        name: zsh
        state: present

    - name: Install oh-my-zsh
      changed_when: "oh-my-zsh already installed"
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
